config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root :to => 'devise/sessions#new'
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new", as: "new_user_registration"
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'friends', to: 'friends#index'
  post 'friends/destroy', to: "friends#destroy"
  resources :friend_requests

  resources :users, only: [:new, :show, :create]
  resources :posts, only: [:index, :create]
  resources :comments, only: [:create]

  resources :searches

  resources :post do
    member do
      post "like_toggle", to: "posts#like_toggle"
    end
  end

  # Action Cable

  mount ActionCable.server, at: '/cable'

  # Aliases

  get '/feed', to: 'posts#index'
end

app/views/partials/_cover_photo_section.html.erb
<div class="user-container">
	<div id="cover-photo" style="background-image: url(<%= @user.cover_photo.url(:large) %>)">

		<div class="name-container shadow">
			<div class="profile-photo-lg" style="background-image: url(<%= @user.profile_photo.url(:medium) %>)">
			</div>
			<div class="profile-photo-name">
				<h1><%= @user.fullname %></h1>
				<% if current_user != @user %>
				<div class="clear-info">
					<i class="fas fa-check"></i>&nbsp;&nbsp;Friends
				</div>
				<% else %>
				<%= link_to edit_user_registration_path do %>
				<div class="clear-info">
					<i class="fas fa-pencil-alt"></i>&nbsp;&nbsp;<%= t('profile.edit_settings') %>
				</div>
				<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/partials/_feed.html.erb
	<%= render @posts %>

	<div id="infinite-scrolling">
		<%= will_paginate @posts %>
	</div>

app/views/partials/_friend_request_button.html.erb
<% if current_user.friends.exists?(user.id) %>
<%= link_to raw("<i class=\"fa fa-check\"></i> Friends"), {:action => "destroy", :controller => "friends", :id => user.id}, method: :post, remote: true, class: "button blue request-remove", id: "friends_action_button-#{user.id}" %>
<% elsif current_user.friend_requests.exists?(friend_id: user.id) %>
<%= link_to raw("<i class=\"fa fa-arrow-right\"></i>Request Sent"), current_user.friend_requests.where(:friend_id == user.id).first, method: :delete, remote: true, class: "button blue request-cancel", id: "friends_action_button-#{user.id}" %>
<% else %>
<%= link_to raw("<i class=\"fa fa-plus\"></i> Add Friend"), {:action => "create", :controller => "friend_requests", :friend_id => user.id}, method: :post, remote: true, class: "button blue", id: "friends_action_button-#{user.id}" %>
<% end %>

app/views/partials/_menusystem.html.erb
<div class="top-nav row middle-xs">
	<div class="col-xs-8 start-xs">
		<div class="search row middle-xs">
			<div class="center-xs">
				<i class="fa fa-search search-icon"></i>
			</div>
			<div class="col-xs">
				<%= form_tag(searches_path) do %>
				<%= hidden_field_tag "search[user_id]", "#{@current_user.id}" %>
				<%= text_field_tag "search[keywords]", params[:keywords], placeholder: "#{get_search_placeholder}", class: "globalsearch" %>
				<% end %>
			</div>
		</div>
	</div>

	<div class="col-xs end-xs">
		<%= button_to logout_path, method: :delete, class: "logout-button" do %>
		<i class="fa fa-sign-out"></i>
		<% end %>
	</div>
</div>
<div class="side-nav">
	<%= link_to(root_url) do %>
	<div class="logo-container">
		<img src="<%= asset_path("logo.svg") %>" class="logo">
	</div>
	<% end %>
	<div class="profile-image" style="background-image: url(<%= current_user.profile_photo_file_name != nil ? current_user.profile_photo.url(:medium) : asset_path("nophoto.png") %>)"></div>

	<div class="icon-row" id="newpost">
		<i class="fa fa-edit"></i>
	</div>

	<%= link_to(:feed) do %>
	<div class="icon-row">
		<i class="fa fa-bars"></i>
	</div>
	<% end %>
	<%= link_to(:friends) do %>
	<div class="icon-row">
		<i class="fa fa-users shrinkify"></i>
	</div>
	<% end %>
	<%= link_to(current_user) do %>
	<div class="icon-row">
		<i class="fa fa-user"></i>
	</div>
	<% end %>
</div>

app/views/partials/_meta.html.erb
<div class="box-container">
	<div class="header">
		<%= t('ui.recent_activity') %>
	</div>
	<div class="box" id="activity">
		<%= render "partials/recent_activity" %>
	</div>

	
	<div id="friend-request-container" <% if !(FriendRequest.where(friend: current_user).all.count > 0) %> style="display: none" <% end %>>
		<div class="header">
			Friend Requests
		</div>
		<div class="box" id="friend-requests-list"><%= render FriendRequest.where(friend: current_user).all %></div>
	</div>

	<div class="header">
		<%= t('ui.groups') %>
	</div>
	<div class="box groups">
		<%= t('ui.part_of_groups_placeholder') %>
	</div>

	<div class="smallprint">
		&copy; 2018 Lukas Romsicki &amp; <a href="#">contributors.</a>
	</div>
</div>

app/views/partials/_nav.html.erb
<div class="top-nav row middle-xs <%= "translucent" unless !defined?(@user.fullname) %>">
	<div class="col-xs start-xs logo-container">
		<%= link_to(:feed) do %>
		<div class="logo" style="background-image: url(<%= asset_path("logo.svg") %>)"></div>
		<% end %>
	</div>

	<div class="col-xs start-xs center-xs hamburger-container">
		<i class="fa fa-bars"></i>
	</div>

	<div class="col-xs">
		<%= form_tag(searches_path) do %>
		<%= hidden_field_tag "search[user_id]", "#{current_user.id}" %>
		<%= text_field_tag "search[keywords]", params[:keywords], placeholder: "#{search_placeholder}", class: "globalsearch" %>
		<% end %>
	</div>

	<div class="col-xs nav-tool center-xs">
		<%= button_to edit_user_registration_path, method: :get, class: "nav-tool_button" do %>
		<i class="fas fa-cog"></i>
		<% end %>
	</div>

	<div class="col-xs nav-tool center-xs">
		<%= button_to destroy_user_session_path, method: :delete, class: "nav-tool_button" do %>
		<i class="fas fa-sign-out-alt"></i>
		<% end %>
	</div>
</div>
<div class="side-nav">
	<%= link_to(current_user) do %>
	<div class="profile-image" style="background-image: url(<%= current_user.profile_photo.url(:medium) %>)"></div>
	<% end %>

	<%= link_to(:feed) do %>
	<div class="icon-row">
		<i class="fas fa-newspaper"></i>
	</div>
	<% end %>
	<div class="icon-row">
		<i class="fas fa-bell"></i>
	</div>
	<div class="icon-row">
		<i class="fas fa-users"></i>
	</div>
	<div class="icon-row">
		<i class="fas fa-comments"></i>
	</div>
	<%= link_to(:friends) do %>
	<div class="icon-row">
		<i class="fas fa-user-friends"></i>
	</div>
	<% end %>
</div>

app/views/partials/_recent_activity.html.erb
You have <strong id="num-friend-requests"><%= FriendRequest.where(friend: current_user).all.count %></strong> friend request<%= FriendRequest.where(friend: current_user).all.count > 1 || FriendRequest.where(friend: current_user).all.count == 0 ? "s" : "" %>.

app/views/partials/_writepost.html.erb
<div id="writepost">
	<div class="post-header">
		<div class="post-header_left">
			<div class="post-header_profile" style="background-image: url(<%= current_user.profile_photo.url(:small) %>)"></div>

			<div class="post-header_activity">
				<%= link_to current_user.fullname, user_path(current_user), class: "link" %>
			</div>
		</div>
	</div>
	<%= form_for :post, :html => { id:  "new_post_form" }, remote: true do |f| -%>
	<%= f.text_field "title", id: "new_post_title", placeholder: t('writepost.title'), :autocomplete => :off %>
	<%= f.text_area "content", id: "new_post_box", placeholder: t('writepost.write'), :autocomplete => :off %>

	<div id="new_post_actions">
		<%= button_tag(type: "button", class: "fab", id: "new_post_add_image") do %>
		<%= f.file_field :image, as: :file, id: "new_post_file" %>
		<i class="fa fa-camera"></i>
		<% end %>

		<%= f.button(type: "submit", class: "fab", id: "new_post_create") do %>
		<i class="fa fa-paper-plane"></i>
		<% end %>
	</div>
	<% end %>

	<div id="new_post_drawer"></div>
</div>

<hr />

app/views/partials/post_page.js.erb
$('#feed').append('<%= j render @posts %>');
<% if @posts.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>